sudo: true

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

compiler:
  - g++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - sudo apt-get install build-essential
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz --no-check-certificate
  - tar xf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  - wget -O boost_1_56_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz/download
  - tar xzvf boost_1_56_0.tar.gz
  - cd boost_1_56_0/
  - wget https://dl.dropboxusercontent.com/u/88131281/install_boost.sh
  - chmod +x install_boost.sh
  - ./install_boost.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
