sudo: true

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.56-all-dev

compiler:
  - g++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - sudo apt-get install build-essential
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz --no-check-certificate
  - tar xf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1
  - ./configure
  - make
  - sudo make install
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
